spring:
    datasource:
      url: jdbc:mysql://localhost:3306/term-commands
      username: term
      password: command
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL57Dialect
      generate-ddl: true
      show-sql: true
    freemarker:
      suffix: .html
    main:
      allow-bean-definition-overriding: true
    application:
      name: category-service

server:
  port: 8200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost:8761