server:
  port: 8080

spring:
  application:
    name: zuul-proxy
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
  instance:
    hostname: discovery:8761

zuul:
  routes:
    category-service:
      url: http://category:8200
      path: /api/categories/**
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie


    command-service:
      path: /api/commands/**
      url: http://command:8500
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

    user-service:
      path: /api/users/**
      url: http://user-service:8400
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie


  host:
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

